### ISSUE TITLE
[Question] Is there a way to use mybinder.org and this setup? 

### ISSUE THREAD

**Issue by dfinke** [trallard/TLJH-azure-button#10]
The deploy worked, no problem, was able to login, no problem.

I'd like to be able to  my repo https://github.com/dfinke/myjupyter and have it spin up using my Azure provisioned infrastructure.

Is this doable?

Thank you

**Comment by trallard** [comment]
Hi just to make sure, you want to spin up your Azure JupyterHub and when you login have the contents of that repo already in there?

If so this might be possible but I have not tried, will have a look 😄

**Comment by dfinke** [comment]
I like that angle. I'm new to the `mybinder` approach. They have a website where I can point to my repo, use my docker file, and spin up the dotnet interactive be pieces. 

An alternative works for me. 

Thank you
