### ISSUE TITLE
404 Page not found after install

### ISSUE THREAD

**Issue by BillmanH** [trallard/TLJH-azure-button#16]
Ran this a few years ago for a project. Worked really well. Today running it in the same way, getting 404. 
<img width="129" alt="image" src="https://user-images.githubusercontent.com/10108711/216512458-cafbfe04-0be4-4176-aca9-78aa6b01a0c6.png">

My script output: 
```
vm:~$ curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py \
>   | sudo python3 - \
>     --admin billmansuper \
>     --show-progress-page
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16481  100 16481    0     0  84953      0 --:--:-- --:--:-- --:--:-- 84953
Existing TLJH installation detected, upgrading...
Upgrading pip...
Upgrading TLJH installer...
Running TLJH installer...
Setting up admin users
Granting passwordless sudo to JupyterHub admins...
Setting up user environment...
Setting up JupyterHub...
Waiting for JupyterHub to come up (1/20 tries)
Done!
```
I notice that this repo hasn't been updated in a while, does this process still work?

**Comment by BillmanH** [comment]
Already fixed it. I found that I was using an "Azure Virtual Machine, hosting Ubuntu 20.04" instead of the "18.4 Ubuntu Server" that your documentation clearly states. 

Making sure to have the right VM made it all work.

**Comment by trallard** [comment]
Thanks for opening this issue. 
While not a bug per se - this might need an upgrade/update so folks can use Ubuntu 20 vs 18.
