### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by jtpio** [trallard/TLJH-azure-button#2]
Really cool to see more options for one-click JupyterHub deployments!

Are there any plans to also support TLJH plugins, for example as extra parameters?

I quickly checked the [azuredeploy.json](https://github.com/trallard/TLJH-azure-button/blob/master/azuredeploy.json) file but couldn't find any reference to it.

**Comment by trallard** [comment]
I had not originally thought about it but I think it can be added without too much fuzz.

I will have a go later and report back ✨

**Comment by jtpio** [comment]
Nice, thanks!

**Comment by trallard** [comment]
@jtpio now this supports plugins! ✨ ✨ Thanks for the suggestion

**Comment by jtpio** [comment]
Great, thanks @trallard!
